name: Publish to NPM

on:
  push:
    branches:
      - main # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish --access public # Adjust options as needed
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
