name: Publish to Yarn

on:
  push:
    branches:
      - main

jobs:
  yarn_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Increment Patch Version
        run: yarn version --patch --new-version $(yarn info your-package-name version).1 --no-git-tag-version

      - name: Publish to Yarn
        run: yarn publish --access public --new-version $(yarn info your-package-name version)
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
