name: Publish to NPM

on:
  push:
    branches:
      - main # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish --access public # Adjust options as needed
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
